"""init

Revision ID: 0
Revises: 
Create Date: 2022-09-11 18:33:35.851821

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('adm_user_pkey'))
    )
    op.create_index(op.f('adm_user_email_idx'), 'adm_user', ['email'], unique=True)
    op.create_index(op.f('adm_user_username_idx'), 'adm_user', ['username'], unique=True)
    op.create_table('adm_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=True),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['adm_user.id'], name=op.f('adm_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('adm_profile_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adm_profile')
    op.drop_index(op.f('adm_user_username_idx'), table_name='adm_user')
    op.drop_index(op.f('adm_user_email_idx'), table_name='adm_user')
    op.drop_table('adm_user')
    # ### end Alembic commands ###
