"""init

Revision ID: 0
Revises: 
Create Date: 2022-09-07 18:40:21.962524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adm_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('adm_user_pkey'))
    )
    op.create_index(op.f('adm_user_email_idx'), 'adm_user', ['email'], unique=True)
    op.create_index(op.f('adm_user_username_idx'), 'adm_user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('adm_user_username_idx'), table_name='adm_user')
    op.drop_index(op.f('adm_user_email_idx'), table_name='adm_user')
    op.drop_table('adm_user')
    # ### end Alembic commands ###
