"""init

Revision ID: 0
Revises: 
Create Date: 2022-11-09 12:01:32.478473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cre_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('scope', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cre_permission_pkey'))
    )
    op.create_index(op.f('cre_permission_scope_idx'), 'cre_permission', ['scope'], unique=True)
    op.create_table('cre_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cre_role_pkey'))
    )
    op.create_table('cre_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cre_user_pkey'))
    )
    op.create_index(op.f('cre_user_email_idx'), 'cre_user', ['email'], unique=True)
    op.create_index(op.f('cre_user_username_idx'), 'cre_user', ['username'], unique=True)
    op.create_table('cre_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('line1', sa.String(length=255), nullable=True),
    sa.Column('line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('province', sa.String(length=255), nullable=True),
    sa.Column('postcode', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['cre_user.id'], name=op.f('cre_profile_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cre_profile_pkey'))
    )
    op.create_table('cre_role_permission',
    sa.Column('cre_role_id', sa.Integer(), nullable=False),
    sa.Column('cre_permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cre_permission_id'], ['cre_permission.id'], name=op.f('cre_role_permission_cre_permission_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cre_role_id'], ['cre_role.id'], name=op.f('cre_role_permission_cre_role_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cre_role_id', 'cre_permission_id', name=op.f('cre_role_permission_pkey'))
    )
    op.create_table('cre_user_role',
    sa.Column('cre_user_id', sa.Integer(), nullable=False),
    sa.Column('cre_role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cre_role_id'], ['cre_role.id'], name=op.f('cre_user_role_cre_role_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cre_user_id'], ['cre_user.id'], name=op.f('cre_user_role_cre_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('cre_user_id', 'cre_role_id', name=op.f('cre_user_role_pkey'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cre_user_role')
    op.drop_table('cre_role_permission')
    op.drop_table('cre_profile')
    op.drop_index(op.f('cre_user_username_idx'), table_name='cre_user')
    op.drop_index(op.f('cre_user_email_idx'), table_name='cre_user')
    op.drop_table('cre_user')
    op.drop_table('cre_role')
    op.drop_index(op.f('cre_permission_scope_idx'), table_name='cre_permission')
    op.drop_table('cre_permission')
    # ### end Alembic commands ###
